### ISSUE TITLE
e-mail could not be sent

### ISSUE THREAD

**Issue by j3k0** [hectane/wordpress-hectane#1]
Hello.

I just installed hectane to use with wordpress (using docker-hectane).

Trying to test by using "recover password" from wordpress but get the following:

```
The e-mail could not be sent.
Possible reason: your host may have disabled the mail() function.
```

The link from wordpress container to hectane seems alright:

``` sh
$ docker exec -it statusggsovh_wordpress_1 bash
# curl -ki https://mail:8025/v1/version
HTTP/1.1 200 OK
Content-Type: application/json
Date: Tue, 20 Oct 2015 06:39:07 GMT
Content-Length: 19

{"version":"0.2.1"}
```

Settings on the wordpress side:

![Settings](https://cdn.pbrd.co/images/1vJjwREz.png)

Anything I should try / be aware of? Nothing appears on either wordpress nor hectane container logs.

Thanks for the effort, I'm looking forward to have it up and running :+1:

**Comment by nathan-osman** [comment]
Thanks for trying this out!

In your screenshot, you have "Use TLS" checked but this will only work if you started the Hectane container with the `TLS_CERT` and `TLS_KEY`  environment variables. If these are not set, Hectane will only listen for HTTP traffic and will become confused when the WordPress plugin attempts to connect via HTTPS.

Don't worry - it's completely safe to run the Hectane container without TLS as long as you don't expose any ports. Only linked containers will have access to it.

If you have set those variables, then something else is causing problems. I set up a test installation of the three containers (Hectane, MySQL, and WordPress) on a clean server to reproduce the issue and ran into a completely unrelated issue with an incorrectly formatted email header.

**Comment by j3k0** [comment]
It is setup using TLS_CERT and TLS_KEY, with a self signed certificate. See the `curl` example (on the issue description), it's using https and working fine.

I will try without TLS.

**Comment by j3k0** [comment]
Ok, it is working without TLS.

**Comment by nathan-osman** [comment]
I just realized that PHP and the cURL extension are probably throwing an error when connecting via TLS due to the self-signed certificate. I'll make sure the next version of the plugin includes an option to ignore certificate errors.

Glad to hear you finally got it working.
