### ISSUE TITLE
HTML emails

### ISSUE THREAD

**Issue by j3k0** [hectane/wordpress-hectane#3]
We're using Formidable (a contact-form wordpress plugin) to send styled emails, but they are sent as plain text (i.e. the HTML is sent as plain text) by hectane wordpress plugin.

I saw that hectane itself supports HTML body, but is this supported by the wordpress plugin as well?

**Comment by nathan-osman** [comment]
No, this is not yet supported by the WordPress plugin, but it is a planned feature.

**Comment by nathan-osman** [comment]
Fixed by version 0.1.3.
