### ISSUE TITLE
Multibyte chars in from name

### ISSUE THREAD

**Issue by supermomonga** [hectane/wordpress-hectane#6]
If the from name contains multibyte chars like `日本語 <foo@example.com>`, It will be fail.

Could you reproduce this problem?

**Comment by nathan-osman** [comment]
I can confirm the error. I'll see if I can figure out what's causing this.

**Comment by nathan-osman** [comment]
This is a bug with Hectane itself, so I'm going to close the bug here and open a new one there.

**Comment by supermomonga** [comment]
Ah, I appreciate it. Thanks!
